In [1]:
import pandas as pd
import numpy as np

/tmp/ipykernel_9367/2162656668.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
df = pd.read_csv("Data/final_data_10.csv")
df

R_ENTERTAINMENT  CAT_CREDIT_CARD  R_CLOTHING_DEBT  R_HEALTH_DEBT  \
0           0.293363              0.0         0.002762       0.000295   
1           0.287582              0.0         0.014518       0.000738   
2           0.573152              0.0         0.001736       0.000837   
3           0.300654              0.0         0.008600       0.001624   
4           0.314731              1.0         0.000631       0.001526   
..               ...              ...              ...            ...   
995         0.286576              1.0         0.002367       0.001280   
996         0.623680              0.0         0.006233       0.001280   
997         0.569382              0.0         0.000000       0.002363   
998         0.303419              1.0         0.002604       0.000689   
999         0.296129              0.0         0.028089       0.101103   

     R_ENTERTAINMENT_DEBT  R_EDUCATION_INCOME  R_DEBT_INCOME  R_GROCERIES  \
0                0.001862            0.000000       0.432425     0.773031   
1                0.017533            0.000000       0.110563     0.487391   
2                0.002184            0.000000       0.467560     0.747555   
3                0.006872            0.102980       0.210807     0.644879   
4                0.000706            0.000000       0.432425     0.448276   
..                    ...                 ...            ...          ...   
995              0.000578            0.000000       0.452082     0.640762   
996              0.013615            0.000000       0.226042     0.625836   
997              0.000000            0.000000       0.221318     0.772259   
998              0.001895            0.503961       0.453444     0.833505   
999              0.054366            0.000000       0.027027     0.533453   

     R_EXPENDITURE_INCOME  R_TAX_DEBT  ...  R_EXPENDITURE_DEBT  T_TAX_12  \
0                0.249944    0.000000  ...            0.006247  0.000000   
1                0.181777    0.016195  ...            0.022208  0.115970   
2                0.249944    0.000000  ...            0.005777  0.000000   
3                0.249944    0.006941  ...            0.012813  0.098454   
4                0.181777    0.004113  ...            0.005677  0.231646   
..                    ...         ...  ...                 ...       ...   
995              0.181777    0.003085  ...            0.005427  0.394522   
996              0.181777    0.010797  ...            0.010864  0.169870   
997              0.300037    0.000000  ...            0.034462  0.000000   
998              0.333258    0.000000  ...            0.006616  0.000000   
999              0.333258    0.021594  ...            0.111051  0.021983   

     T_FINES_12  R_EXPENDITURE  R_DEBT_SAVINGS  CAT_GAMBLING  T_FINES_6  \
0      0.000000       0.711912        0.004098           1.0   0.000000   
1      0.000000       0.320078        0.011820           0.0   0.000000   
2      0.025334       0.694415        0.084394           1.0   0.033272   
3      0.000000       0.568399        0.033294           1.0   0.000000   
4      0.000000       0.501060        0.006988           1.0   0.000000   
..          ...            ...             ...           ...        ...   
995    0.000000       0.605161        0.012823           1.0   0.000000   
996    0.000000       0.438848        0.026180           0.0   0.000000   
997    0.000000       1.000000        0.002476           0.0   0.000000   
998    0.000000       0.836515        0.257831           0.0   0.000000   
999    0.000000       0.525097        0.000488           0.0   0.000000   

     R_GROCERIES_DEBT  R_UTILITIES_DEBT  CREDIT_SCORE  
0            0.002984          0.001717         0.288  
1            0.005443          0.009089         0.650  
2            0.002656          0.001616         0.338  
3            0.002361          0.003535         0.518  
4            0.004754          0.004343         0.346  
..                ...               ...           ...

In [4]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,:-1], df.iloc[:,-1], test_size=0.2, random_state=63)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((800, 22), (200, 22), (800,), (200,))

In [5]:
from Models.LinearRegression import LinearRegressionModel

# Create an instance of the LinearRegressionModel class
model = LinearRegressionModel("First")
print(model.trained)
model.train(x_train, y_train)
print(model.trained)
model.predict(x_test)

for sctype in ["MAE", "MSE", "RMSE", "R2", "MAPE"]:
    print(sctype,"->", model.score(y_test, score_type=sctype))

2024-03-09 18:12:30.294 | ERROR    | Models.abstract_model:trained:23 - First is not trained yet
2024-03-09 18:12:30.297 | INFO     | Models.abstract_model:train:30 - Model was trained successfully: status:True


False
True
MAE -> 0.035958159154637
MSE -> 0.0022952183038585624
RMSE -> 0.04790843666681853
R2 -> 0.8675516508024951
MAPE -> 0.0755292037592301


In [6]:
from Models.RidgeRegression import RidgeRegressionModel

# Create an instance of the RidgeRegressionModel class
model = RidgeRegressionModel("First Ridge Model")
print(model.trained)
model.train(x_train, y_train)
print(model.trained)
model.predict(x_test)

for sctype in ["MAE", "MSE", "RMSE", "R2", "MAPE"]:
    print(sctype,"->", model.score(y_test, score_type=sctype))

2024-03-09 18:12:30.316 | ERROR    | Models.abstract_model:trained:23 - First Ridge Model is not trained yet
2024-03-09 18:12:30.318 | INFO     | Models.abstract_model:train:30 - Model was trained successfully: status:True


False
True
MAE -> 0.036284493729960336
MSE -> 0.0022895682509717847
RMSE -> 0.04784943313114362
R2 -> 0.8678776939402978
MAPE -> 0.07919923503669157


In [7]:
model.save()

2024-03-09 18:12:30.344 | INFO     | Models.abstract_model:save:80 - Model saved to saved_models/First Ridge Model.pkl


In [8]:
model_loaded = model.load()

2024-03-09 18:12:30.385 | INFO     | Models.abstract_model:load:92 - Model loaded from saved_models/First Ridge Model.pkl


In [9]:
from Models.LassoRegression import LassoRegressionModel

# Create an instance of the LassoRegressionModel class
model = LassoRegressionModel("First Lasso Model", alpha=0.001)
print(model.trained)
model.train(x_train, y_train)
print(model.trained)
model.predict(x_test)

for sctype in ["MAE", "MSE", "RMSE", "R2", "MAPE"]:
    print(sctype,"->", model.score(y_test, score_type=sctype))

2024-03-09 18:12:30.424 | ERROR    | Models.abstract_model:trained:23 - First Lasso Model is not trained yet
2024-03-09 18:12:30.450 | INFO     | Models.abstract_model:train:30 - Model was trained successfully: status:True


False
True
MAE -> 0.03823103869804309
MSE -> 0.002449349546962852
RMSE -> 0.04949090367898784
R2 -> 0.8586573209365284
MAPE -> 0.08032683719410894


In [10]:
model.cross_validate(x_train, y_train, cv=5, scoring="r2")

[0.7870188  0.75270632 0.82963637 0.80391989 0.79681073]


0.7940184238163297

In [11]:
from Utils.GridSearch import grid_search

In [15]:
params = {
        "alpha" :np.linspace(0.000013, 0.1, 10),
        "max_iter": list(range(51, 100, 7)),
        "selection": ["cyclic", "random"]
}
result = grid_search(LassoRegressionModel, x_train, y_train, params)
result

/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.397e-01, tolerance: 1.044e-03
  model = cd_fast.enet_coordinate_descent(
/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.604e-01, tolerance: 9.373e-04
  model = cd_fast.enet_coordinate_descent(
/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not conv

[0.78925256 0.7755866  0.82738816 0.81536207 0.80134778]
[0.7895881  0.77539794 0.82688432 0.81572181 0.80180863]


/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.391e-01, tolerance: 1.044e-03
  model = cd_fast.enet_coordinate_descent(
/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.380e-03, tolerance: 9.373e-04
  model = cd_fast.enet_coordinate_descent(
/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not conv

[0.7895274  0.77558118 0.82740593 0.81540619 0.80148971]
[0.78945073 0.77554124 0.82727982 0.81563818 0.80166562]
[0.78939811 0.7755724  0.82741049 0.81540861 0.80148703]


/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.252e-02, tolerance: 1.014e-03
  model = cd_fast.enet_coordinate_descent(
/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.519e-03, tolerance: 1.038e-03
  model = cd_fast.enet_coordinate_descent(
/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not conv

[0.78931892 0.77559253 0.82741629 0.81552969 0.80160126]
[0.78930392 0.77557304 0.82741049 0.81539505 0.80145647]


/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.137e-03, tolerance: 1.014e-03
  model = cd_fast.enet_coordinate_descent(
/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.221e-03, tolerance: 1.038e-03
  model = cd_fast.enet_coordinate_descent(
/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not conv

[0.78933283 0.7756523  0.82742467 0.81548857 0.80154268]
[0.78927074 0.77557727 0.82741049 0.81538022 0.80143695]


/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.397e-03, tolerance: 1.014e-03
  model = cd_fast.enet_coordinate_descent(
/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.038e-03, tolerance: 1.044e-03
  model = cd_fast.enet_coordinate_descent(
/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not conv

[0.78931119 0.77562159 0.82745736 0.81545697 0.8014991 ]
[0.78927618 0.77557727 0.82741049 0.81536964 0.80143695]


/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.254e-03, tolerance: 1.014e-03
  model = cd_fast.enet_coordinate_descent(
/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.074e-03, tolerance: 1.044e-03
  model = cd_fast.enet_coordinate_descent(
/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not conv

[0.78929887 0.77566979 0.82745415 0.81542885 0.80146811]
[0.78928756 0.77557727 0.82741049 0.81536503 0.80143695]
[0.78930418 0.77560802 0.82743497 0.81541999 0.80145359]


/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.935e-02, tolerance: 9.373e-04
  model = cd_fast.enet_coordinate_descent(
/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.636e-03, tolerance: 9.976e-04
  model = cd_fast.enet_coordinate_descent(
/home/erikaramovich/Documents/MtqiZark/credit_score_prediction/venv/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not conv

[0.41622172 0.32666814 0.3846492  0.40230971 0.38992916]
[0.41622172 0.32666814 0.3846492  0.40230971 0.38992916]
[0.41622172 0.32666814 0.3846492  0.40230971 0.38992916]
[0.41622172 0.32666814 0.3846492  0.40230971 0.38992916]
[0.41622172 0.32666814 0.3846492  0.40230971 0.38992916]
[0.41622172 0.32666814 0.3846492  0.40230971 0.38992916]
[0.41622172 0.32666814 0.3846492  0.40230971 0.38992916]
[0.41622172 0.32666814 0.3846492  0.40230971 0.38992916]
[0.41622172 0.32666814 0.3846492  0.40230971 0.38992916]
[0.41622172 0.32666814 0.3846492  0.40230971 0.38992916]
[0.41622172 0.32666814 0.3846492  0.40230971 0.38992916]
[0.41622172 0.32666814 0.3846492  0.40230971 0.38992916]
[0.41622172 0.32666814 0.3846492  0.40230971 0.38992916]
[0.41622172 0.32666814 0.3846492  0.40230971 0.38992916]
[-2.58429314e-05 -1.80318960e-03 -1.57360344e-03 -4.05407354e-03
 -4.92860280e-03]
[-2.58429314e-05 -1.80318960e-03 -1.57360344e-03 -4.05407354e-03
 -4.92860280e-03]
[-2.58429314e-05 -1.80318960e-03 -1.

{'alpha': 1.3e-05,
 'max_iter': 58,
 'selection': 'random',
 'best_score': 0.8019151177993002}

In [14]:
from preprocessing.check_outliers import CheckOutliers

check = CheckOutliers(df)
df = check.transform()


2024-03-11 20:32:20.255 | INFO     | preprocessing.check_outliers:transform:33 - Number of outliers in dataframe 39


In [15]:
df

R_ENTERTAINMENT  CAT_CREDIT_CARD  R_CLOTHING_DEBT  R_HEALTH_DEBT  \
0           0.293363              0.0         0.002762       0.000295   
1           0.287582              0.0         0.014518       0.000738   
2           0.573152              0.0         0.001736       0.000837   
3           0.300654              0.0         0.008600       0.001624   
4           0.314731              1.0         0.000631       0.001526   
..               ...              ...              ...            ...   
995         0.286576              1.0         0.002367       0.001280   
996         0.623680              0.0         0.006233       0.001280   
997         0.569382              0.0         0.000000       0.002363   
998         0.303419              1.0         0.002604       0.000689   
999         0.296129              0.0         0.028089       0.101103   

     R_ENTERTAINMENT_DEBT  R_EDUCATION_INCOME  R_DEBT_INCOME  R_GROCERIES  \
0                0.001862            0.000000       0.432425     0.773031   
1                0.017533            0.000000       0.110563     0.487391   
2                0.002184            0.000000       0.467560     0.747555   
3                0.006872            0.102980       0.210807     0.644879   
4                0.000706            0.000000       0.432425     0.448276   
..                    ...                 ...            ...          ...   
995              0.000578            0.000000       0.452082     0.640762   
996              0.013615            0.000000       0.226042     0.625836   
997              0.000000            0.000000       0.221318     0.772259   
998              0.001895            0.503961       0.453444     0.833505   
999              0.054366            0.000000       0.027027     0.533453   

     R_EXPENDITURE_INCOME  R_TAX_DEBT  ...  R_EXPENDITURE_DEBT  T_TAX_12  \
0                0.249944    0.000000  ...            0.006247  0.000000   
1                0.181777    0.016195  ...            0.022208  0.115970   
2                0.249944    0.000000  ...            0.005777  0.000000   
3                0.249944    0.006941  ...            0.012813  0.098454   
4                0.181777    0.004113  ...            0.005677  0.231646   
..                    ...         ...  ...                 ...       ...   
995              0.181777    0.003085  ...            0.005427  0.394522   
996              0.181777    0.010797  ...            0.010864  0.169870   
997              0.300037    0.000000  ...            0.034462  0.000000   
998              0.333258    0.000000  ...            0.006616  0.000000   
999              0.333258    0.021594  ...            0.111051  0.021983   

     T_FINES_12  R_EXPENDITURE  R_DEBT_SAVINGS  CAT_GAMBLING  T_FINES_6  \
0      0.000000       0.711912        0.004098           1.0   0.000000   
1      0.000000       0.320078        0.011820           0.0   0.000000   
2      0.025334       0.694415        0.084394           1.0   0.033272   
3      0.000000       0.568399        0.033294           1.0   0.000000   
4      0.000000       0.501060        0.006988           1.0   0.000000   
..          ...            ...             ...           ...        ...   
995    0.000000       0.605161        0.012823           1.0   0.000000   
996    0.000000       0.438848        0.026180           0.0   0.000000   
997    0.000000       1.000000        0.002476           0.0   0.000000   
998    0.000000       0.836515        0.257831           0.0   0.000000   
999    0.000000       0.525097        0.000488           0.0   0.000000   

     R_GROCERIES_DEBT  R_UTILITIES_DEBT  CREDIT_SCORE  
0            0.002984          0.001717         0.288  
1            0.005443          0.009089         0.650  
2            0.002656          0.001616         0.338  
3            0.002361          0.003535         0.518  
4            0.004754          0.004343         0.346  
..                ...               ...           ...

In [17]:
check_1 = CheckOutliers(df)
df = check.transform()
df

2024-03-11 20:33:05.273 | INFO     | preprocessing.check_outliers:transform:33 - Number of outliers in dataframe 49


R_ENTERTAINMENT  CAT_CREDIT_CARD  R_CLOTHING_DEBT  R_HEALTH_DEBT  \
0           0.293363              0.0         0.002762       0.000295   
1           0.287582              0.0         0.014518       0.000738   
2           0.573152              0.0         0.001736       0.000837   
3           0.300654              0.0         0.008600       0.001624   
4           0.314731              1.0         0.000631       0.001526   
..               ...              ...              ...            ...   
995         0.286576              1.0         0.002367       0.001280   
996         0.623680              0.0         0.006233       0.001280   
997         0.569382              0.0         0.000000       0.002363   
998         0.303419              1.0         0.002604       0.000689   
999         0.296129              0.0         0.028089       0.101103   

     R_ENTERTAINMENT_DEBT  R_EDUCATION_INCOME  R_DEBT_INCOME  R_GROCERIES  \
0                0.001862            0.000000       0.432425     0.773031   
1                0.017533            0.000000       0.110563     0.487391   
2                0.002184            0.000000       0.467560     0.747555   
3                0.006872            0.102980       0.210807     0.644879   
4                0.000706            0.000000       0.432425     0.448276   
..                    ...                 ...            ...          ...   
995              0.000578            0.000000       0.452082     0.640762   
996              0.013615            0.000000       0.226042     0.625836   
997              0.000000            0.000000       0.221318     0.772259   
998              0.001895            0.503961       0.453444     0.833505   
999              0.054366            0.000000       0.027027     0.533453   

     R_EXPENDITURE_INCOME  R_TAX_DEBT  ...  R_EXPENDITURE_DEBT  T_TAX_12  \
0                0.249944    0.000000  ...            0.006247  0.000000   
1                0.181777    0.016195  ...            0.022208  0.115970   
2                0.249944    0.000000  ...            0.005777  0.000000   
3                0.249944    0.006941  ...            0.012813  0.098454   
4                0.181777    0.004113  ...            0.005677  0.231646   
..                    ...         ...  ...                 ...       ...   
995              0.181777    0.003085  ...            0.005427  0.394522   
996              0.181777    0.010797  ...            0.010864  0.169870   
997              0.300037    0.000000  ...            0.034462  0.000000   
998              0.333258    0.000000  ...            0.006616  0.000000   
999              0.333258    0.021594  ...            0.111051  0.021983   

     T_FINES_12  R_EXPENDITURE  R_DEBT_SAVINGS  CAT_GAMBLING  T_FINES_6  \
0      0.000000       0.711912        0.004098           1.0   0.000000   
1      0.000000       0.320078        0.011820           0.0   0.000000   
2      0.025334       0.694415        0.084394           1.0   0.033272   
3      0.000000       0.568399        0.033294           1.0   0.000000   
4      0.000000       0.501060        0.006988           1.0   0.000000   
..          ...            ...             ...           ...        ...   
995    0.000000       0.605161        0.012823           1.0   0.000000   
996    0.000000       0.438848        0.026180           0.0   0.000000   
997    0.000000       1.000000        0.002476           0.0   0.000000   
998    0.000000       0.836515        0.257831           0.0   0.000000   
999    0.000000       0.525097        0.000488           0.0   0.000000   

     R_GROCERIES_DEBT  R_UTILITIES_DEBT  CREDIT_SCORE  
0            0.002984          0.001717         0.288  
1            0.005443          0.009089         0.650  
2            0.002656          0.001616         0.338  
3            0.002361          0.003535         0.518  
4            0.004754          0.004343         0.346  
..                ...               ...           ...